### ISSUE TITLE
Feature Request : Allow HTML in news widget

### ISSUE THREAD

**Issue by ramesh-dada** [afrux/news-widget#1]
Sometimes in order to take users to blog or any other page for documentation or anything else we need to link a text with a tag.

**Comment by SychO9** [comment]
I'd probably use lite markdown formatting instead, it does the job and is more readable.

**Comment by ramesh-dada** [comment]
Thanks I am ok with markdown I just want to add a link.

**Comment by bkil** [comment]
We would also need this. Our use case is very similar: we only need to provide a single link along with the message (to a Jitsi or BigBlueButton conference or an event) Do you perhaps have a simple workaround just to support this?

**Comment by SychO9** [comment]
> Do you perhaps have a simple workaround just to support this?

Unfortunately there are no workarounds, I haven't had time to implement this yet, I'll see if I can get to it sometime this week.
